### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

###Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "Mololor sit amet",
  "date": "2021-01-01T12:00:00Z",
  "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  "priority": "normal",
  "status": "todo"
}

### Update A Task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
  "id": "472474c0-02ab-4f2f-a9cd-ce6fe8316012",
  "status": "inProgress"
}